server:
  port: 8088

spring:
  redis:
    database: 10
    host: 172.21.0.6
    port: 6379
    timeout: 1000
  data:
    mongodb:
      uri: mongodb://172.21.0.7:27017/ddbms
      database: ddbms
    hdfs:
      uri: hdfs://172.21.0.2:9000